// Generated from Azul Zulu packaged OpenJDK JAR and carries the same GPL license with the classpath exception
package rt

type Java__lang__reflect__AnnotatedElement__Static struct{}

var Java__lang__reflect__AnnotatedElement__Var Java__lang__reflect__AnnotatedElement__Static

func Java__lang__reflect__AnnotatedElement() *Java__lang__reflect__AnnotatedElement__Static {
	return &Java__lang__reflect__AnnotatedElement__Var
}

type Java__lang__reflect__AnnotatedElement__Instance interface {
	GetAnnotation__desc____obj__Java__lang__Class__ret____obj__Java__lang__annotation__Annotation(Java__lang__Class__Instance) Java__lang__annotation__Annotation__Instance
	GetClass__desc____ret____obj__Java__lang__Class() Java__lang__Class__Instance
	Finalize__desc____ret__V()
	GetAnnotations__desc____ret____arr____obj__Java__lang__annotation__Annotation() ObjectArray__Instance
	GetDeclaredAnnotation__desc____obj__Java__lang__Class__ret____obj__Java__lang__annotation__Annotation(Java__lang__Class__Instance) Java__lang__annotation__Annotation__Instance
	NotifyAll__desc____ret__V()
	Wait__desc____ret__V()
	HashCode__desc____ret__I() int
	GetAnnotationsByType__desc____obj__Java__lang__Class__ret____arr____obj__Java__lang__annotation__Annotation(Java__lang__Class__Instance) ObjectArray__Instance
	Wait__desc__J__I__ret__V(int64, int)
	GetDeclaredAnnotationsByType__desc____obj__Java__lang__Class__ret____arr____obj__Java__lang__annotation__Annotation(Java__lang__Class__Instance) ObjectArray__Instance
	Clone__desc____ret____obj__Java__lang__Object() Java__lang__Object__Instance
	Wait__desc__J__ret__V(int64)
	IsAnnotationPresent__desc____obj__Java__lang__Class__ret__Z(Java__lang__Class__Instance) bool
	Equals__desc____obj__Java__lang__Object__ret__Z(Java__lang__Object__Instance) bool
	GetDeclaredAnnotations__desc____ret____arr____obj__Java__lang__annotation__Annotation() ObjectArray__Instance
	Notify__desc____ret__V()
	ToString__desc____ret____obj__Java__lang__String() Java__lang__String__Instance
	RawPtr__Java__lang__Object() *Java__lang__Object__Impl
}

func Java__lang__reflect__AnnotatedElement__defaultmethod__GetAnnotationsByType__desc____obj__Java__lang__Class__ret____arr____obj__Java__lang__annotation__Annotation(this Java__lang__reflect__AnnotatedElement__Instance, var0 Java__lang__Class__Instance) ObjectArray__Instance {
	panic("Method not implemented - java/lang/reflect/AnnotatedElement.getAnnotationsByType(Ljava/lang/Class;)[Ljava/lang/annotation/Annotation;")
}

func Java__lang__reflect__AnnotatedElement__defaultmethod__GetDeclaredAnnotation__desc____obj__Java__lang__Class__ret____obj__Java__lang__annotation__Annotation(this Java__lang__reflect__AnnotatedElement__Instance, var0 Java__lang__Class__Instance) Java__lang__annotation__Annotation__Instance {
	panic("Method not implemented - java/lang/reflect/AnnotatedElement.getDeclaredAnnotation(Ljava/lang/Class;)Ljava/lang/annotation/Annotation;")
}

func Java__lang__reflect__AnnotatedElement__defaultmethod__GetDeclaredAnnotationsByType__desc____obj__Java__lang__Class__ret____arr____obj__Java__lang__annotation__Annotation(this Java__lang__reflect__AnnotatedElement__Instance, var0 Java__lang__Class__Instance) ObjectArray__Instance {
	panic("Method not implemented - java/lang/reflect/AnnotatedElement.getDeclaredAnnotationsByType(Ljava/lang/Class;)[Ljava/lang/annotation/Annotation;")
}

func Java__lang__reflect__AnnotatedElement__defaultmethod__IsAnnotationPresent__desc____obj__Java__lang__Class__ret__Z(this Java__lang__reflect__AnnotatedElement__Instance, var0 Java__lang__Class__Instance) bool {
	panic("Method not implemented - java/lang/reflect/AnnotatedElement.isAnnotationPresent(Ljava/lang/Class;)Z")
}

type Java__lang__reflect__GenericDeclaration__Static struct{}

var Java__lang__reflect__GenericDeclaration__Var Java__lang__reflect__GenericDeclaration__Static

func Java__lang__reflect__GenericDeclaration() *Java__lang__reflect__GenericDeclaration__Static {
	return &Java__lang__reflect__GenericDeclaration__Var
}

type Java__lang__reflect__GenericDeclaration__Instance interface {
	GetAnnotation__desc____obj__Java__lang__Class__ret____obj__Java__lang__annotation__Annotation(Java__lang__Class__Instance) Java__lang__annotation__Annotation__Instance
	GetClass__desc____ret____obj__Java__lang__Class() Java__lang__Class__Instance
	Finalize__desc____ret__V()
	GetAnnotations__desc____ret____arr____obj__Java__lang__annotation__Annotation() ObjectArray__Instance
	GetDeclaredAnnotation__desc____obj__Java__lang__Class__ret____obj__Java__lang__annotation__Annotation(Java__lang__Class__Instance) Java__lang__annotation__Annotation__Instance
	NotifyAll__desc____ret__V()
	Wait__desc____ret__V()
	HashCode__desc____ret__I() int
	GetAnnotationsByType__desc____obj__Java__lang__Class__ret____arr____obj__Java__lang__annotation__Annotation(Java__lang__Class__Instance) ObjectArray__Instance
	Wait__desc__J__I__ret__V(int64, int)
	GetDeclaredAnnotationsByType__desc____obj__Java__lang__Class__ret____arr____obj__Java__lang__annotation__Annotation(Java__lang__Class__Instance) ObjectArray__Instance
	Clone__desc____ret____obj__Java__lang__Object() Java__lang__Object__Instance
	Wait__desc__J__ret__V(int64)
	IsAnnotationPresent__desc____obj__Java__lang__Class__ret__Z(Java__lang__Class__Instance) bool
	Equals__desc____obj__Java__lang__Object__ret__Z(Java__lang__Object__Instance) bool
	GetDeclaredAnnotations__desc____ret____arr____obj__Java__lang__annotation__Annotation() ObjectArray__Instance
	Notify__desc____ret__V()
	ToString__desc____ret____obj__Java__lang__String() Java__lang__String__Instance
	RawPtr__Java__lang__Object() *Java__lang__Object__Impl
}

type Java__lang__reflect__Type__Static struct{}

var Java__lang__reflect__Type__Var Java__lang__reflect__Type__Static

func Java__lang__reflect__Type() *Java__lang__reflect__Type__Static {
	return &Java__lang__reflect__Type__Var
}

type Java__lang__reflect__Type__Instance interface {
	GetClass__desc____ret____obj__Java__lang__Class() Java__lang__Class__Instance
	Finalize__desc____ret__V()
	NotifyAll__desc____ret__V()
	Wait__desc____ret__V()
	HashCode__desc____ret__I() int
	GetTypeName__desc____ret____obj__Java__lang__String() Java__lang__String__Instance
	Wait__desc__J__I__ret__V(int64, int)
	Clone__desc____ret____obj__Java__lang__Object() Java__lang__Object__Instance
	Wait__desc__J__ret__V(int64)
	Equals__desc____obj__Java__lang__Object__ret__Z(Java__lang__Object__Instance) bool
	Notify__desc____ret__V()
	ToString__desc____ret____obj__Java__lang__String() Java__lang__String__Instance
	RawPtr__Java__lang__Object() *Java__lang__Object__Impl
}

func Java__lang__reflect__Type__defaultmethod__GetTypeName__desc____ret____obj__Java__lang__String(this Java__lang__reflect__Type__Instance) Java__lang__String__Instance {
	panic("Method not implemented - java/lang/reflect/Type.getTypeName()Ljava/lang/String;")
}
