// Generated from Azul Zulu packaged OpenJDK JAR and carries the same GPL license with the classpath exception
package rt

type Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Static struct{}

var Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Var Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Static

func Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction() *Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Static {
	return &Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Var
}

func (this *Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Static) New() *Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Impl {
	v := &Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Impl{
		Java__lang__Object__Impl: Java__lang__Object().New(),
	}
	v.Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__InitDispatch(v)
	return v
}

type Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Dispatch interface {
	Java__lang__Object__Dispatch
	Impl__Run__desc____ret____obj__Java__lang__Object() Java__lang__Object__Instance
}

func (this *Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Impl) Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__InitDispatch(v Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Dispatch) {
	this.Java__lang__Object__Impl.Java__lang__Object__InitDispatch(v)
	this._dispatch = v
}

func (this *Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Impl) Run__desc____ret____obj__Java__lang__Object() Java__lang__Object__Instance {
	return this._dispatch.Impl__Run__desc____ret____obj__Java__lang__Object()
}

type Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Instance interface {
	GetClass__desc____ret____obj__Java__lang__Class() Java__lang__Class__Instance
	Finalize__desc____ret__V()
	NotifyAll__desc____ret__V()
	Wait__desc____ret__V()
	HashCode__desc____ret__I() int
	Run__desc____ret____obj__Java__lang__Object() Java__lang__Object__Instance
	Wait__desc__J__I__ret__V(int64, int)
	Clone__desc____ret____obj__Java__lang__Object() Java__lang__Object__Instance
	Wait__desc__J__ret__V(int64)
	Equals__desc____obj__Java__lang__Object__ret__Z(Java__lang__Object__Instance) bool
	Notify__desc____ret__V()
	ToString__desc____ret____obj__Java__lang__String() Java__lang__String__Instance
	RawPtr__Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction() *Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Impl
	RawPtr__Java__lang__Object() *Java__lang__Object__Impl
}

type Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Impl struct {
	*Java__lang__Object__Impl
	_dispatch Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Dispatch
}

func (this *Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Impl) Impl__Instance_Init__desc____ret__V() {
	panic("Method not implemented - jdk/internal/reflect/ReflectionFactory$GetReflectionFactoryAction.<init>()V")
}

func (this *Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Impl) Impl__Run__desc____ret____obj__Java__lang__Object() Java__lang__Object__Instance {
	panic("Method not implemented - jdk/internal/reflect/ReflectionFactory$GetReflectionFactoryAction.run()Ljava/lang/Object;")
}

func (this *Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Impl) RawPtr__Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction() *Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Impl {
	return this
}

func (this *Jdk__internal__reflect__ReflectionFactory__innerclass__GetReflectionFactoryAction__Impl) Impl_Self() Java__lang__Object__Instance {
	return this
}
