// Generated from Azul Zulu packaged OpenJDK JAR and carries the same
// GPL license with the classpath exception
package rt

type Java__lang__reflect__AnnotatedElement__Static struct{}

var Java__lang__reflect__AnnotatedElement__Var Java__lang__reflect__AnnotatedElement__Static

func Java__lang__reflect__AnnotatedElement() *Java__lang__reflect__AnnotatedElement__Static {
	return &Java__lang__reflect__AnnotatedElement__Var
}

type Java__lang__reflect__AnnotatedElement__Instance interface {
	Clone__desc____ret____obj__Java__lang__Object() Java__lang__Object__Instance
	Equals__desc____obj__Java__lang__Object__ret__Z(Java__lang__Object__Instance) bool
	Finalize__desc____ret__V()
	GetClass__desc____ret____obj__Java__lang__Class() Java__lang__Class__Instance
	HashCode__desc____ret__I() int
	IsAnnotationPresent__desc____obj__Java__lang__Class__ret__Z(Java__lang__Class__Instance) bool
	Notify__desc____ret__V()
	NotifyAll__desc____ret__V()
	ToString__desc____ret____obj__Java__lang__String() Java__lang__String__Instance
	Wait__desc____ret__V()
	Wait__desc__J__ret__V(int64)
	Wait__desc__J__I__ret__V(int64, int)
}

func Java__lang__reflect__AnnotatedElement__defaultmethod__IsAnnotationPresent__desc____obj__Java__lang__Class__ret__Z(this Java__lang__reflect__AnnotatedElement__Instance, var0 Java__lang__Class__Instance) bool {
	panic("Not Implemented - java/lang/reflect/AnnotatedElement.isAnnotationPresent(Ljava/lang/Class;)Z")
}

type Java__lang__reflect__GenericDeclaration__Static struct{}

var Java__lang__reflect__GenericDeclaration__Var Java__lang__reflect__GenericDeclaration__Static

func Java__lang__reflect__GenericDeclaration() *Java__lang__reflect__GenericDeclaration__Static {
	return &Java__lang__reflect__GenericDeclaration__Var
}

type Java__lang__reflect__GenericDeclaration__Instance interface {
	Clone__desc____ret____obj__Java__lang__Object() Java__lang__Object__Instance
	Equals__desc____obj__Java__lang__Object__ret__Z(Java__lang__Object__Instance) bool
	Finalize__desc____ret__V()
	GetClass__desc____ret____obj__Java__lang__Class() Java__lang__Class__Instance
	HashCode__desc____ret__I() int
	IsAnnotationPresent__desc____obj__Java__lang__Class__ret__Z(Java__lang__Class__Instance) bool
	Notify__desc____ret__V()
	NotifyAll__desc____ret__V()
	ToString__desc____ret____obj__Java__lang__String() Java__lang__String__Instance
	Wait__desc____ret__V()
	Wait__desc__J__ret__V(int64)
	Wait__desc__J__I__ret__V(int64, int)
}

type Java__lang__reflect__Type__Static struct{}

var Java__lang__reflect__Type__Var Java__lang__reflect__Type__Static

func Java__lang__reflect__Type() *Java__lang__reflect__Type__Static {
	return &Java__lang__reflect__Type__Var
}

type Java__lang__reflect__Type__Instance interface {
	Clone__desc____ret____obj__Java__lang__Object() Java__lang__Object__Instance
	Equals__desc____obj__Java__lang__Object__ret__Z(Java__lang__Object__Instance) bool
	Finalize__desc____ret__V()
	GetClass__desc____ret____obj__Java__lang__Class() Java__lang__Class__Instance
	GetTypeName__desc____ret____obj__Java__lang__String() Java__lang__String__Instance
	HashCode__desc____ret__I() int
	Notify__desc____ret__V()
	NotifyAll__desc____ret__V()
	ToString__desc____ret____obj__Java__lang__String() Java__lang__String__Instance
	Wait__desc____ret__V()
	Wait__desc__J__ret__V(int64)
	Wait__desc__J__I__ret__V(int64, int)
}

func Java__lang__reflect__Type__defaultmethod__GetTypeName__desc____ret____obj__Java__lang__String(this Java__lang__reflect__Type__Instance) Java__lang__String__Instance {
	panic("Not Implemented - java/lang/reflect/Type.getTypeName()Ljava/lang/String;")
}
