// Generated from Azul Zulu packaged OpenJDK JAR and carries the same GPL license with the classpath exception
package rt

type Jdk__internal__misc__JavaLangAccess__Static struct{}

var Jdk__internal__misc__JavaLangAccess__Var Jdk__internal__misc__JavaLangAccess__Static

func Jdk__internal__misc__JavaLangAccess() *Jdk__internal__misc__JavaLangAccess__Static {
	return &Jdk__internal__misc__JavaLangAccess__Var
}

type Jdk__internal__misc__JavaLangAccess__Instance interface {
	GetClass__desc____ret____obj__Java__lang__Class() Java__lang__Class__Instance
	GetEnumConstantsShared__desc____obj__Java__lang__Class__ret____arr____obj__Java__lang__Enum(Java__lang__Class__Instance) ObjectArray__Instance
	InvokeFinalize__desc____obj__Java__lang__Object__ret__V(Java__lang__Object__Instance)
	Finalize__desc____ret__V()
	FastUUID__desc__J__J__ret____obj__Java__lang__String(int64, int64) Java__lang__String__Instance
	NewStringUnsafe__desc____arr__C__ret____obj__Java__lang__String(CharArray__Instance) Java__lang__String__Instance
	NotifyAll__desc____ret__V()
	Wait__desc____ret__V()
	HashCode__desc____ret__I() int
	GetRawClassAnnotations__desc____obj__Java__lang__Class__ret____arr__B(Java__lang__Class__Instance) ByteArray__Instance
	GetRawClassTypeAnnotations__desc____obj__Java__lang__Class__ret____arr__B(Java__lang__Class__Instance) ByteArray__Instance
	Wait__desc__J__I__ret__V(int64, int)
	Clone__desc____ret____obj__Java__lang__Object() Java__lang__Object__Instance
	Wait__desc__J__ret__V(int64)
	RegisterShutdownHook__desc__I__Z____obj__Java__lang__Runnable__ret__V(int, bool, Java__lang__Runnable__Instance)
	Equals__desc____obj__Java__lang__Object__ret__Z(Java__lang__Object__Instance) bool
	Notify__desc____ret__V()
	FindBootstrapClassOrNull__desc____obj__Java__lang__ClassLoader____obj__Java__lang__String__ret____obj__Java__lang__Class(Java__lang__ClassLoader__Instance, Java__lang__String__Instance) Java__lang__Class__Instance
	GetDeclaredAnnotationMap__desc____obj__Java__lang__Class__ret____obj__Java__util__Map(Java__lang__Class__Instance) Java__util__Map__Instance
	Packages__desc____obj__Java__lang__ClassLoader__ret____obj__Java__util__stream__Stream(Java__lang__ClassLoader__Instance) Java__util__stream__Stream__Instance
	ToString__desc____ret____obj__Java__lang__String() Java__lang__String__Instance
	RawPtr__Java__lang__Object() *Java__lang__Object__Impl
}
